### ISSUE TITLE
Mobile >> Brasa Slider Responsivo

### ISSUE THREAD

**Issue by LuwkasLima** [brasadesign/securegen-theme#1]
@diegorojas, penso que seria interessante deixar o Brasa Slider (ou qualquer slider usado nessa area) responsivo, mas com um tamanho melhor para dispositivos com tela pequena. Minha sugestao eh deixa-lo com a largura da tela e portanto aumentar sua altura proporcionalmente (evitando impactar a imagem).

![image](https://cloud.githubusercontent.com/assets/5949986/20636322/95f183ba-b330-11e6-995a-7340740d7e8b.png)

**Comment by diegorojas** [comment]
Lucas, não consegui deixar o Slider mais alta na versão responsiva. Sem distorcer a imagem as informações ficariam cortadas. Precisariamos pensr para um versão de imagens e do slider mais quadrados para dar certo, sacou?
